site_name: Token Risk Classification
site_description: Token Risk Classification
repo_url: https://github.com/cryptousersecurity/token-risk-classification
repo_name: token-risk-classification
strict: true
theme:
  name: "material"
  language: en
  features:
    - content.code.copy
    - navigation.tabs
markdown_extensions:
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Risk Types:
    - TRC-001 Honeypot: TRC-001.md
    - TRC-002 Mintable: TRC-002.md
    - TRC-003 OwnershipRetrieval: TRC-003.md
    - TRC-004 BalanceManipulation: TRC-004.md
    - TRC-005 HiddenOwnership: TRC-005.md
    - TRC-006 SelfDestruction: TRC-006.md
    - TRC-007 ExternalInvocation: TRC-007.md
    - TRC-008 BlackListFunction: TRC-008.md
    - TRC-009 FullSaleRestriction: TRC-009.md
    - TRC-010 SlippageModification: TRC-010.md
    - TRC-011 TransferPausable: TRC-011.md
    - TRC-012 PersonalSlippageModification: TRC-012.md
    - TRC-013 TransactionWhitelisting: TRC-013.md
    - TRC-014 AntiWhale: TRC-014.md
    - TRC-015 AntiWhaleModification: TRC-015.md
    - TRC-016 TradingCooldown: TRC-016.md
  - Contributing: contributing.md
