site_name: Token Security Benchmark
site_description: Token Security Benchmark
repo_url: https://github.com/cryptousersecurity/token-security-benchmark
repo_name: token-security-benchmark
strict: true
theme:
  name: "material"
  language: en
  features:
    - content.code.copy
    - navigation.tabs
markdown_extensions:
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Risk Types:
    - TSB-001 Honeypot: TSB-001.md
    - TSB-002 Mintable: TSB-002.md
    - TSB-003 OwnershipRetrieval: TSB-003.md
    - TSB-004 BalanceManipulation: TSB-004.md
    - TSB-005 HiddenOwnership: TSB-005.md
    - TSB-006 SelfDestruction: TSB-006.md
    - TSB-007 ExternalInvocation: TSB-007.md
    - TSB-008 BlackListFunction: TSB-008.md
    - TSB-009 FullSaleRestriction: TSB-009.md
    - TSB-010 SlippageModification: TSB-010.md
    - TSB-011 TransferPausable: TSB-011.md
    - TSB-012 PersonalSlippageModification: TSB-012.md
    - TSB-013 TransactionWhitelisting: TSB-013.md
    - TSB-014 AntiWhale: TSB-014.md
    - TSB-015 AntiWhaleModification: TSB-015.md
    - TSB-016 TradingCooldown: TSB-016.md
  - Contributing: contributing.md
